### ISSUE TITLE
Android Studio dependsOn in multi module project

### ISSUE THREAD

**Issue by nenick** [evant/android-studio-unit-test-plugin#24]
I like the way to use `tasks.findByName("assembleDebug").dependsOn("testDebugClasses")` but i have issues to use this way with a multi module setup. One module is an Android application and the other one is an Android library module which is used by the application module.

When using the dependsOn way i have to write the dependsOn line in both build.gradle files. The line only works at the application module. The line at both or only at the library module throws following error.

```
Circular dependency between the following tasks:
:Data:assembleDebug
\--- :Data:testDebugClasses
     \--- :Data:compileTestDebugJava
          \--- :Data:mergeDebugTestResources
               +--- :Data:assembleDebug (*)
               \--- :Data:generateDebugTestResources
                    \--- :Data:compileDebugTestRenderscript
                         \--- :Data:processDebugTestManifest
                              \--- :Data:assembleDebug (*)
```

To support multi module project i can use the second way with the run configuration but i prefer the other one. 

So the question is, have you an idea to support the dependsOn way on multi module projects with android studio?

**Comment by Sid666999** [comment]
I update to 1.4.0 and recreate my JUnit run configurations but this issue still happens.
