### ISSUE TITLE
Test sourceSet not marked for android library modules

### ISSUE THREAD

**Issue by schroepf** [evant/android-studio-unit-test-plugin#37]
I have a project which is set up similar to: https://github.com/JCAndKSolutions/android-unit-test/tree/master/example
- an app module (build.gradle: `apply plugin: 'com.android.application'`)
- a library module (build.gradle: `apply plugin: 'com.android.library'`)
For both modules I've applied the android-unit-test gradle plugin, but:
- for the library module the `test` source set is not properly marked in android studio as test sources and I cannot run the tests
- app module works just fine

I figured out, that when I manually edit the librarie's `.iml` file I can fix this. What I had to change was:
- add: `<output-test url="file://$MODULE_DIR$/build/test-classes/debug" />`
- add: `<sourceFolder url="file://$MODULE_DIR$/src/test/java" isTestSource="true" />`
- add: `<orderEntry type="library" exported="" scope="TEST" name="junit-4.11" level="project" />`
- and add: `<orderEntry type="library" exported="" scope="TEST" name="hamcrest-core-1.3" level="project" />`
and then I'm able to run junit tests just fine...

**Comment by schroepf** [comment]
... it just came to my mind that I should mention that I have defined two productFlavors for my library project... maybe this is what causes the problems...

**Comment by evant** [comment]
I'm assuming that running `gradle test` on the command line runs the tests correctly?

**Comment by schroepf** [comment]
Correct. From the command line I can run the tests just fine.

**Comment by schroepf** [comment]
I think the issue was caused by my project setup. The gradle dependencies of the app module were broken and thus Android Studio could not resolve the dependencies correctly:

Before it was like this:

        compile project(path: ':library', configuration: 'communityRelease')

I changed it to:

    releaseCompile project(path: ':library', configuration: 'communityRelease')
    debugCompile project(path: ':library', configuration: 'communityDebug')

and now the sourceSets of the test tasks are marked correctly as test case files.
