### ISSUE TITLE
How to setup this project

### ISSUE THREAD

**Issue by nenick** [evant/android-studio-unit-test-plugin#41]
Can you explain what i must do to get this project compile?

I like to see whether this could be ported to support https://github.com/novoda/gradle-android-test-plugin I like to have the possibility to use robolectric in a separate module. But it need some configuration/hacks to use it inside android studio.

**Comment by evant** [comment]
You should be able to just open it in intellij. Though you will probably have to fix the paths to the platform plugin sdk and dependent plugins. (You can find them in `<android-studio-path>/plugins/android/lib` and `<android-studio-path>/plugins/gradle/lib`.

In order to get this to work with another gradle plugin, you need to register a custom artifact with all the configuration information to the android plugin. See https://github.com/JCAndKSolutions/android-unit-test/blob/master/src/main/groovy/com/jcandksolutions/gradle/androidunittest/ModelManager.groovy for an example. You shouldn't need to modify this plugin at all, unless you want to add new features.

However, why do you want to do this? I'm no longer maintaining this project since a proper unit testing solution is out now.

**Comment by nenick** [comment]
This new feature does not support to have robolectric test in a separated module. I need this for different test setups. Example setup is to have unit tests with robolectric inside main module (done with the new feature), component/integration tests (best done in a separated module so they don't mix with unit tests) and full integration tests with instrumentation/espresso in main module.

I have intellij 13 Ultimate installed and tried to open your project with it but without success. As plugin lib source I use Android Studio 1.1.0
- as jdk I set java 1.7
- edit android plugin dependency path to `<android-studio-path>/plugins/android/lib` (was wrong path)
- edit gradle plugin dependency path to `<android-studio-path>/plugins/gradle/lib` (was pointing to <intellij>/plugins/gradle/lib`
- mark the src folder as source path

Then `Make Project` tells me it miss `import com.intellij.openapi`dependencies. I found an openapi lib at `<android-studio-path>/lib` but it still miss some classes from openapi.

`import com.intellij.openapi.diagnostic.Logger;`
`import com.intellij.openapi.roots.impl.libraries.ProjectLibraryTable;`

At GrepCode I found a version where this classes exists. http://grepcode.com/snapshot/repository.grepcode.com/java/ext/com.jetbrains/intellij-idea/13.0.0/

Now I tells me it miss

`import com.android.annotations.NonNull;`
`import com.android.annotations.Nullable;`

You have an idea what I did wrong?

**Comment by evant** [comment]
I've only tested with intellij 14, so I don't know if that may cause any issues. Make sure you set the project SDK to the "Intellij Platform Plugin SDK" (you may have to create one if it doesn't exist. For the annotations, it's safe to replace them with

```
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
```

Sorry about that, I may have had some other dependency in there, but when I just opened the project, those were missing for me as well.

I really think this is going to be far too much effort for what you want to achieve. What is wrong with having the robolectric tests in the same module but in a different directory? If you want to separate tests, you can just create two separate directories and add them both to the 'test' source set.

**Comment by evant** [comment]
Another note, make sure you set the dependency scope for the android and gradle plugins as "provided". Otherwise you will get runtime errors due to conflicting instances.

**Comment by evant** [comment]
Sorry about the difficulty building, for my future intellij plugins, I've adopted a different strategy that makes it far easier to build https://github.com/evant/holdr/blob/master/intellij-plugin/build.gradle . If you want to do any significant work on this, I'd advise you porting it over to that instead.

**Comment by nenick** [comment]
Thanks for your help. Now I have it compiling. Later i will look if it "works".

One annoying issue is that `BuildVariantView.BuildVariantSelectionChangeListener` changed with AndroidStudio 1.1.0 so we don't get `List<AndroidFacet>` at this point.

The approach to have just two different test src folders in one module looks possible but I see some disadvantages.
- When I have two test folders at same time added then a simple `gradle test` would execute them together. But we prefer to run them separated because one includes fast unit tests and the other the much slower component tests (and we have more than just two test strategies with robolectric).
- When we add them only when we need them with mark directory (or some gradle logic) we don't have both visible in android studio so that usage searches and refactoring will miss one.
- Same issue is already known with connectedAndroidTests and unit test, only one can be used at same time.

Another approach I did is to have multiple application modules and move my application code to a library (application could not depend on other application module). This looks a bit strange to have many application modules with AndroidManifest and some other stuff so that it does compile and I can run the unit tests. But yes this would be the best supported way for Android Studio and my needs.

At next comes the migration costs and thats a reason why we don't like to change the project structure (change build chains, teach co workers, ...)

And the most important point is that I need a project where I can learn plugin development ;)

**Comment by nenick** [comment]
Updated: 

Looks like your plugin works with Android Studio 1.1.0 without errors. I expected errors because of missing possibility to access List<AndroidFacet> but it run my Android Studio 1.0.0 example with success.

Next test case give errors ..
`me.tatarka.androidunittest.idea.AndroidStudioGradleUnitTestPluginComponent$1.buildVariantsConfigChanged()V:      me.tatarka.androidunittest.idea.AndroidStudioGradleUnitTestPluginComponent$1.buildVariantsConfigChanged()V`

**Comment by nenick** [comment]
Thank you for your help. Perhaps you are right it is to much effort.
